### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/image-uploads#22]
- [x] Current example uses blueimp and jquery to perform the request to S3 - re-write in vanilla XHR
- [x] Convert the server from express to hapi
- [x] Add tests for server
- [x] Return bucket name as an environment variable from the server
- [x] Add end-to-end tests (nightwatch) #15

**Comment by nelsonic** [comment]
closing as this is complete. ✅ 
Thanks again @jackcarlisle ❤️
