### ISSUE TITLE
Example/Showcase of Image Upload UX/UI?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-uploads#46]
Image uploading is a common feature in _many_ web/mobile applications. 

> We are going to be using the Image Upload feature _extensively_ in [**`Time`**](https://github.com/dwyl/time) 
to allow people to upload a photo showing evidence of their **_completed_ activity**.
(_if you cannot visualise the use-case of this, **please comment** in_: https://github.com/dwyl/time/issues/215)

Additionally there are _several_ classes of applications where image uploading is relevant:
+ Dedicated Photo Sharing App (_the obvious one_) 
+ Messaging/Chat (_where "a picture is worth a thousand words"_) Look no further than [SnapChat!](https://en.wikipedia.org/wiki/Snapchat)
+ Personal/Company Finance & Accounting (_Uploading Receipts_)

# Todo

+ [ ] Create an start-to-finish Image Upload Example 
+ [ ] Deploy it to Heroku
+ [ ] Make the code _generic_ and _modular_ so that _anyone_ can use it in their project.

Questions we need to ask/answer:
+ [ ] How do we _secure_ our `/upload` endpoint to avoid people using it maliciously to upload undesirable images. 
  + [ ] Can we restrict the `Origin` of the upload? 
    + [ ] Can the `Origin` be _spoofed_ by a command-line script?

> I'm not saying that we are _going_ to create an "image upload" **product**,
But the ability to upload files/images is a "standalone" feature that people _pay_ for! 
e.g: https://apps.shopify.com/uploadery
> This is a feature that has _real_ value to end-users so if we build something _great_
> not only will the people using the @dwyl app find it _useful_, 
> the wider _community_ will use it and _help_ us to _improve_ it!

**Comment by nelsonic** [comment]
+ https://www.smashingmagazine.com/2018/01/drag-drop-file-uploader-vanilla-js/
+ https://aws.amazon.com/blogs/compute/resize-images-on-the-fly-with-amazon-s3-aws-lambda-and-amazon-api-gateway/

**Comment by nelsonic** [comment]
This is probably the approach we are going to follow: 
https://aws.amazon.com/solutions/serverless-image-handler/

**Comment by nelsonic** [comment]
testing uploading image in GitHub with JS disabled.

**Comment by nelsonic** [comment]
@RobStallion this morning I'm starting with this: 
https://docs.aws.amazon.com/solutions/latest/serverless-image-handler/welcome.html
It looks like it will get us more than half way to our goal.

**Comment by nelsonic** [comment]
Signing up for a Brand New AWS account to take advantage of the 12 months of free tier. **`#NoBrainer`**

**Comment by nelsonic** [comment]
They've improved the on-boarding ...
![image](https://user-images.githubusercontent.com/194400/58234340-3442a680-7d36-11e9-8a3e-4e6da2e4e421.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/58319790-32e6ac00-7e12-11e9-9e05-e77ecf11e17b.png)

**Comment by iteles** [comment]
Woah, that's WAY more than I thought it would be!

**Comment by nelsonic** [comment]
Potential Elixir implementation: https://github.com/stavro/arc
