### ISSUE TITLE
Epic: Image Classifier

### ISSUE THREAD

**Issue by nelsonic** [dwyl/image-uploads#52]
Once we are uploading images #51 
We want to classify the images and suggest meta tags to describe the images so that they become "searchable".
That means pulling any text out of images using OCR.
And attempting to find any detail in images that can be useful.

We aren't going build our own models from scratch. but we are going to ...

# Todo

+ [ ] Research the available models, services/APIs we can use to send an image that classify images
+ [ ] Research available OCR services or models.
  + [ ] If there is an _Open Source_ OCR model we can run on our own infra e.g. €20/month on Fly.io share!!

@LuchoTurtle please leave comments with your research. 🙏

**Comment by LuchoTurtle** [comment]
Stumbled upon these two, which might be relevant to revisit at a later stage:
https://github.com/bentoml/OpenLLM
https://github.com/showlab/Image2Paragraph

**Comment by nelsonic** [comment]
Yeah, saw `OpenLLM` on HN this morning: 
<img width="857" alt="openllm-top-hn" src="https://github.com/dwyl/imgup/assets/194400/644e1769-2444-49ea-96ba-29bc4f596938">
https://news.ycombinator.com/item?id=36388219
Looks good. `BentoML` is what `OpenAI` _could_ have been but they chose to go closed (MSFT) ... 🙄

**Comment by LuchoTurtle** [comment]
I've thought about what would be the best way of doing this and I've found a fair share of resources that I think may help get something close to what we want.

# Image Captioning models

Most common **open-source LLMs**, such as Llama2 or Claude2, only receive text input. I took a gander at https://github.com/bentoml/OpenLLM, as I've stated in the comment above. However, it's not really useful to us as these LLms **do not understand image inputs** (though maybe some of these can understand vectorial representations of images). Therefore, we have to forgo these more "mainstream" LLMs for this use case.

There are, however, models pertaining to computer vision we can definitely use. I started my dive in https://github.com/salesforce/LAVIS#image-captioning, which led to me discovering [`BLIP-2`](https://huggingface.co/spaces/Salesforce/BLIP2), a [zero-shot](https://deepchecks.com/glossary/zero-shot-learning/) image-to-text generation model that we can use for image captioning.

I'm not going to explain how `BLIP-2` works but you can find more info about it at https://huggingface.co/blog/blip-2. The good thing about it is that it's available in [Hugging Face Transformers](https://github.com/huggingface/transformers), which we can easily use to download and run `BLIP-2` as a pre-trained model quite easily, even if it's just for testing purposes.

You can find a demo at https://huggingface.co/spaces/Salesforce/BLIP2.

# Langchain 🦜

I had heard about Langchain several times for a few months, and how it makes it easy to create LLM-based applications, and *chain* different models together to yield a given output for a person for whatever use case. And the fact that you can easily deploy it to [`fly.io`](https://fly.io/blog/deploying-langchain-to-fly-io/) is a big plus.

I was thinking of using `BLIP-2` and chaining it to an open-source LLM like Llama 2 or the others, to get a more descriptive caption of the image, so we could extract keywords afterwards.

# `Image2Paragraph`

However, I realised that I was doing something similar to [`Image2Paragraph`](https://zhaohengyuan1.github.io/image2paragraph.github.io/), which does something similar to this, but with the added capabilities of two models: `GRIT` and `Segment Anything`, which provide *contextual descriptions* of images. The output of all three models (`BLIP-2`, `GRIT`, `Segment Anything) are later fed to an LLM (GPT, in this case) to generate a text paragraph describing the image.

Here's how the pipeline works: 

![image](https://github.com/dwyl/imgup/assets/17494745/af66aaad-f2f2-4ff9-b5d6-bdee45a6a326)

# So what to use?

You should give `Image2Paragraph` a whirl (I already tried on Hugging Faces but it's not working https://huggingface.co/spaces/Awiny/Image2Paragraph) but I don't see a clear way of using it to receive an image URL and output the paragraph *and deploy this on `fly.io`*. If I can only have this on `localhost`, there's no point in pursuing this.

So I wonder if only using `BLIP-2` or using [`vit-gpt2-image-captioning`](https://huggingface.co/nlpconnect/vit-gpt2-image-captioning) models from HuggingFace is easier and more "doable" for what we want.

(The latter seems like a highly plausible option using transformers. See https://ankur3107.github.io/blogs/the-illustrated-image-captioning-using-transformers/).

**Comment by nelsonic** [comment]
Good research/summary. Thanks. 👌

**Comment by LuchoTurtle** [comment]
As @nelsonic suggested, we can give https://github.com/elixir-image/image a whirl, as well.

**Comment by nelsonic** [comment]
@LuchoTurtle I've lowered the priority on this issue to reflect the fact that it's a _very_ "nice to have" feature but isn't "core" to the experience of our `App` for the time being. We need to focus on the `WYSIWYG` editor and getting the "core" functionality done and then shipping the `Flutter` App to the `App Store` ASAP. ⏳

**Comment by nelsonic** [comment]
It will be an _awesome_ enhancement to add image recognition to the images people upload in the `Flutter` App. 
But if we don't yet have a `Flutter` App deployed to the `App Store` or `Google Play` we are a ["Default Dead"](http://www.paulgraham.com/aord.html) company.

**Comment by nelsonic** [comment]
@LuchoTurtle given that we are `BLOCKED` on both `iOS App Store` https://github.com/dwyl/app/issues/342#issuecomment-1770978159 and `Google Play` https://github.com/dwyl/app/issues/346 both assigned to @iteles 🔥 
Please take a look at this issue today. 
We should create a `new` repo for it: https://github.com/dwyl/image-classifier 🆕 ✅ 
Feel free to use `Python` for it if you think you can do it _faster_. 🐍 
Otherwise if you can use `Elixir`, it will be easier for us to maintain longer-term. 💧
